# Generated by Django 3.1.4 on 2021-04-21 07:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.TextField(unique=True)),
                ('gender', models.IntegerField(choices=[(0, '남성'), (1, '여성')])),
                ('age', models.PositiveIntegerField()),
                ('joinday', models.DateTimeField(auto_now_add=True)),
                ('limit', models.IntegerField()),
                ('profile', models.URLField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
