# Generated by Django 3.1.4 on 2021-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id', 'joinday']},
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default='account', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_detail',
            field=models.TextField(default='address_detail'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_number',
            field=models.TextField(default='00000'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.CharField(default='bank', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
