# Generated by Django 3.1.4 on 2021-06-18 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(default='', max_length=50)),
                ('add_or_sub', models.BooleanField(default=True)),
                ('point', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'pointlist',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nanuda.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='review_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='nationalinfo',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_company',
            field=models.CharField(blank=True, default='SKT', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='point_entire',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanuda.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanuda.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanuda.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[('1', '남성'), ('0', '여성')], default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='01090373600', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nanuda.pointlist'),
        ),
    ]
