# Generated by Django 3.1.4 on 2021-04-21 08:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0002_auto_20210421_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='나누다', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(blank=True, default='계좌', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_detail',
            field=models.TextField(blank=True, default='상세주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_number',
            field=models.TextField(blank=True, default='우편번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank',
            field=models.CharField(blank=True, default='은행', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('service_score', models.FloatField(blank=True, default=5.0)),
                ('service_content', models.CharField(blank=True, max_length=300, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanuda.user')),
            ],
            options={
                'db_table': 'servicereview',
                'ordering': ['id', 'service_date'],
            },
        ),
    ]
