# Generated by Django 3.1.4 on 2021-04-22 01:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0003_auto_20210421_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(blank=True, default='제품 종류', max_length=10)),
                ('product_source', models.URLField()),
                ('product_name', models.CharField(blank=True, default='제품 이름', max_length=10)),
                ('product_price', models.PositiveIntegerField()),
                ('product_image', models.URLField()),
                ('product_stock', models.PositiveIntegerField()),
                ('product_option', models.JSONField(default=dict)),
                ('product_option_price', models.PositiveIntegerField()),
                ('product_shipping_price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'product',
                'ordering': ['id', 'product_type', 'product_price'],
            },
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nanuda.user'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('review_content', models.TextField(blank=True, default='내용')),
                ('review_image', models.URLField()),
                ('review_alert', models.IntegerField(default=0)),
                ('review_rating', models.IntegerField(default=0)),
                ('review_follower', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nanuda.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nanuda.user')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['id', 'review_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_price', models.PositiveIntegerField()),
                ('order_amount', models.PositiveIntegerField()),
                ('order_method', models.CharField(default='배달', max_length=10)),
                ('order_expected_date', models.JSONField(default=dict)),
                ('order_upfront_date', models.DateTimeField(blank=True)),
                ('order_receiver', models.CharField(default='수령인', max_length=30)),
                ('order_address_number', models.TextField(default='우편번호')),
                ('order_address', models.TextField(default='주소')),
                ('order_address_detail', models.TextField(default='상세주소')),
                ('order_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('order_request', models.TextField(default='주문 요청사항')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nanuda.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nanuda.user')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['id', 'order_date'],
            },
        ),
    ]
