# Generated by Django 3.1.4 on 2021-06-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0003_auto_20210623_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.PositiveIntegerField(default=30000),
        ),
    ]
