# Generated by Django 3.1.4 on 2021-04-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0004_auto_20210422_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.URLField(blank=True),
        ),
    ]
