# Generated by Django 3.1.4 on 2021-06-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0005_auto_20210624_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_dislikeNum',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_likeNum',
            field=models.JSONField(default=list),
        ),
    ]
