# Generated by Django 3.1.4 on 2021-04-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0005_auto_20210422_1103'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servicereview',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
