# Generated by Django 3.2 on 2021-04-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0006_auto_20210422_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
