# Generated by Django 3.1.4 on 2021-06-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0006_auto_20210625_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
