# Generated by Django 3.2 on 2021-04-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0007_user_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='', max_length=300),
        ),
    ]
