# Generated by Django 3.1.4 on 2021-06-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0007_user_billing_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_alert',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
