# Generated by Django 3.1.4 on 2021-06-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0008_auto_20210625_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_dislikeNum',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_likeNum',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
