# Generated by Django 3.2 on 2021-04-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0008_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='limit',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
