# Generated by Django 3.1.4 on 2021-06-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0009_auto_20210625_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_alert',
            field=models.JSONField(blank=True, default={'data': []}),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_dislikeNum',
            field=models.JSONField(blank=True, default={'data': []}, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_likeNum',
            field=models.JSONField(blank=True, default={'data': []}, null=True),
        ),
    ]
