# Generated by Django 3.1.4 on 2021-06-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0010_auto_20210625_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pay',
            field=models.TextField(default=''),
        ),
    ]
