# Generated by Django 3.2 on 2021-04-23 04:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0010_auto_20210423_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='limit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=0, max_length=128, region=None),
        ),
    ]
