# Generated by Django 3.2 on 2021-04-23 04:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0011_auto_20210423_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+821090373600', max_length=128, region=None),
        ),
    ]
