# Generated by Django 3.1.4 on 2021-06-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0014_auto_20210628_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_alert',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_dislikeNum',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_likeNum',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
