# Generated by Django 3.2 on 2021-05-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0014_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
