# Generated by Django 3.1.4 on 2021-05-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0016_servicereview_service_opinion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_content',
            new_name='review_dislike',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_follower',
            new_name='review_dislikeNum',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_rating',
            new_name='review_likeNum',
        ),
        migrations.AddField(
            model_name='review',
            name='review_like',
            field=models.TextField(blank=True, default='내용'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_score',
            field=models.FloatField(blank=True, default=5.0),
        ),
    ]
