# Generated by Django 3.1.4 on 2021-05-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0017_auto_20210506_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereview',
            name='user_id',
        ),
    ]
