# Generated by Django 3.1.4 on 2021-06-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0017_auto_20210628_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_dislikeNum',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
