# Generated by Django 3.1.4 on 2021-05-11 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0018_remove_servicereview_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nanuda.user'),
        ),
    ]
