# Generated by Django 3.1.4 on 2021-06-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0018_auto_20210628_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_dislikeNum',
            field=models.JSONField(),
        ),
    ]
