# Generated by Django 3.2 on 2021-05-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0020_auto_20210511_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.TextField(blank=True, default='', unique=True),
        ),
    ]
