# Generated by Django 3.1.4 on 2021-06-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0020_auto_20210628_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_dislikeNum',
            field=models.JSONField(null=True),
        ),
    ]
