# Generated by Django 3.1.4 on 2021-05-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0021_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
