# Generated by Django 3.1.4 on 2021-06-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0021_auto_20210628_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_alert',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_dislikeNum',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_likeNum',
            field=models.TextField(default=''),
        ),
    ]
