# Generated by Django 3.1.4 on 2021-06-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0022_auto_20210628_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='wish_url',
            field=models.CharField(blank=True, default='http://', max_length=1000),
        ),
    ]
