# Generated by Django 3.1.4 on 2021-06-28 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0024_auto_20210628_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_alert',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_dislikeNum',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_likeNum',
        ),
        migrations.CreateModel(
            name='ReviewList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=30)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanuda.review')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nanuda.user')),
            ],
            options={
                'ordering': ['user_id', 'review_id'],
                'managed': True,
            },
        ),
    ]
