# Generated by Django 3.1.4 on 2021-05-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0025_auto_20210513_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.JSONField(default=list),
        ),
    ]
