# Generated by Django 3.2 on 2021-06-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0025_auto_20210628_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_complete',
            field=models.BooleanField(default=False),
        ),
    ]
