# Generated by Django 3.2 on 2021-05-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0026_auto_20210513_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_claim',
            field=models.CharField(default='문 앞', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
