# Generated by Django 3.1.4 on 2021-06-29 02:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0026_order_order_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wish_des',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wish_haul',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wish_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wish_title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wish_url',
        ),
        migrations.CreateModel(
            name='WishDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='01210413135901010000', max_length=30)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_price', models.PositiveIntegerField(default=30000)),
                ('order_amount', models.PositiveIntegerField(default=0)),
                ('order_method', models.CharField(default='배달', max_length=10)),
                ('order_expected_date', models.JSONField(default=dict)),
                ('order_receiver', models.CharField(default='수령인', max_length=30)),
                ('order_address_number', models.TextField(default='우편번호')),
                ('order_address', models.TextField(default='주소')),
                ('order_address_detail', models.TextField(default='상세주소')),
                ('order_phone_number', models.CharField(default='', max_length=30)),
                ('order_request', models.TextField(default='주문 요청사항')),
                ('order_pay', models.TextField(default='')),
                ('order_detail', models.CharField(blank=True, default='', max_length=100)),
                ('order_total', models.TextField(default='')),
                ('order_shipPrice', models.PositiveIntegerField(default=0)),
                ('wish_haul', models.CharField(blank=True, default='', max_length=30)),
                ('wish_url', models.CharField(blank=True, default='http://', max_length=1000)),
                ('wish_title', models.CharField(blank=True, default='', max_length=1000)),
                ('wish_des', models.CharField(blank=True, default='', max_length=1000)),
                ('wish_image', models.CharField(blank=True, default='', max_length=1000)),
                ('review_write', models.BooleanField(default=False)),
                ('order_complete', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanuda.user')),
            ],
            options={
                'ordering': ['id', 'order_date'],
                'managed': True,
            },
        ),
    ]
