# Generated by Django 3.1.4 on 2021-05-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0026_auto_20210513_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
