# Generated by Django 3.1.4 on 2021-06-29 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0027_auto_20210629_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='', max_length=30)),
                ('payment', models.BooleanField(default=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanuda.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanuda.user')),
            ],
            options={
                'ordering': ['user_id', 'order_id'],
                'managed': True,
            },
        ),
    ]
