# Generated by Django 3.2 on 2021-05-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0027_auto_20210513_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_name',
            field=models.CharField(default='나누다씨', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='address_phone',
            field=models.CharField(default='01090373600', max_length=30),
        ),
    ]
