# Generated by Django 3.2 on 2021-05-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0027_auto_20210513_1718'),
        ('nanuda', '0028_auto_20210514_1325'),
    ]

    operations = [
    ]
