# Generated by Django 3.1.4 on 2021-06-29 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0028_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='wish_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nanuda.wishdeal'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nanuda.order'),
        ),
    ]
