# Generated by Django 3.2 on 2021-05-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0030_user_address_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_exist',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
