# Generated by Django 3.2 on 2021-06-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0030_paymenthistory_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
