# Generated by Django 3.2 on 2021-05-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0031_user_bank_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_phone_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
