# Generated by Django 3.2 on 2021-06-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0031_paymenthistory_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='money',
            field=models.PositiveIntegerField(),
        ),
    ]
