# Generated by Django 3.2 on 2021-05-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0032_alter_order_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='01210413135901010000', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='wish_des',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='wish_haul',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='wish_image',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='wish_title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='wish_url',
            field=models.CharField(blank=True, default='http://', max_length=30),
        ),
    ]
