# Generated by Django 3.1.4 on 2021-05-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0033_auto_20210518_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
