# Generated by Django 3.2 on 2021-06-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0033_review_wish_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='billing_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='point_entire',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
