# Generated by Django 3.2 on 2021-06-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0034_auto_20210630_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
