# Generated by Django 3.2 on 2021-05-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0034_auto_20210520_1028'),
        ('nanuda', '0035_remove_order_product_id'),
    ]

    operations = [
    ]
