# Generated by Django 3.2 on 2021-07-05 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0035_remove_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('problem', models.CharField(default='', max_length=30)),
                ('problem_detail', models.CharField(default='', max_length=30)),
                ('order_total', models.CharField(blank=True, default='', max_length=10000)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nanuda.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanuda.user')),
                ('wish_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nanuda.wishdeal')),
            ],
            options={
                'ordering': ['user_id', 'order_id'],
                'managed': True,
            },
        ),
    ]
