# Generated by Django 3.2 on 2021-07-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0036_refundproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundproduct',
            name='order_total',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='refundproduct',
            name='problem_detail',
            field=models.CharField(default='', max_length=300),
        ),
    ]
