# Generated by Django 3.1.4 on 2021-05-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0036_merge_20210520_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
