# Generated by Django 3.2 on 2021-07-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0037_auto_20210705_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dupinfo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
