# Generated by Django 3.1.4 on 2021-05-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0037_auto_20210520_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(blank=True, default=''),
        ),
    ]
