# Generated by Django 3.2 on 2021-05-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanuda', '0036_merge_20210520_1044'),
        ('nanuda', '0037_auto_20210520_1116'),
    ]

    operations = [
    ]
